include: package:flutter_lints/flutter.yaml

plugins:
  soco_lints:
    path: ./soco_lints
    diagnostics:
      require_sizes_prefix_import: true

formatter:
  page_width: 120
<<<<<<< HEAD
  trailing_commas: preserve
=======
  trailing_commas: preserve
>>>>>>> 2263fd5 (adjust list format)
