name: soco
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.1.0
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  soco_lints:
    path: ./soco_lints

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
