name: soco_lints
description: Custom lint rules for the Soco app.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: any
  analysis_server_plugin: ^0.3.0
  analyzer_plugin: ^0.14.0

dev_dependencies:
  lints: ^6.1.0