name: soco_lints
description: Custom lint rules for Soco using analysis_server_plugin.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: any
  analyzer_plugin: any
  analysis_server_plugin: '>=0.3.8'
