name: Verify Code Quality

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    name: Analyze and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      
      - name: Install Dependencies
        run: flutter pub get
      
      - name: Check Formatting
        run: dart format -o none --set-exit-if-changed .

      - name: Run Static Analysis
        # Analyze each file independently to ensure the analysis plugin is used
        # Workaround for the follwing bug: https://github.com/dart-lang/sdk/issues/62710
        run: find lib -name "*.dart" | xargs dart analyze

      - name: Run Custom Lint Analysis
        run: dart run custom_lint

      # - name: Run Unit Tests
      #   run: flutter test
